config/routes.rb
IJobDossier::Application.routes.draw do
  root :to => 'job_application_pools#welcome'

  resources :job_application_pools, :as => 'pools' do
    resources :job_applications, :as => "applications" do
      member do
        get :target
        get :dossier
      end
    end
  end

  resources :dossiers do
    resource :curriculum_vitae, :as => 'cv'
    resource :cover_letter, :as => 'cletter' do
      resources :cover_letter_parts, :as => 'part', :only => [ :show, :create, :update, :destroy ]
    end
    resources :references, :as => 'ref'
    resources :work_certificates, :as => 'wcert'
  end

end

app/models/job_application_pool.rb
# == Schema Information
#
# Table name: job_application_pools
#
#  id          :integer          not null, primary key
#  user        :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class JobApplicationPool < ActiveRecord::Base
  attr_accessible :user, :description

  has_many :job_applications, dependent: :destroy

  validates :user, presence: true,
                   length: { minimum: 5, maximum: 10 }

end

app/controllers/job_application_pools_controller.rb
class JobApplicationPoolsController < ApplicationController
  layout "main"

  # GET / root
  def welcome
    @job_application_pools = JobApplicationPool.find(:all, order: 'ID asc')
    @job_application_pool = JobApplicationPool.new
  end

  # GET /job_application_pools(.:format) pools
  def index
    @job_application_pools = JobApplicationPool.find(:all, order: 'ID asc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @job_application_pools }
    end
  end

  # GET /job_application_pools/:id(.:format) pool
  def show
    @job_application_pool = JobApplicationPool.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job_application_pool }
    end
  end

  # GET /job_application_pools/new(.:format) new_pool
  def new
    @job_application_pool = JobApplicationPool.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job_application_pool }
      format.js
    end
  end

  # GET /job_application_pools/:id/edit(.:format) edit_pool
  def edit
    @job_application_pool = JobApplicationPool.find(params[:id])
  end

  # POST /job_application_pools(.:format)
  def create
    @job_application_pool = JobApplicationPool.new(params[:job_application_pool])

    respond_to do |format|
      begin
        @job_application_pool.save!
        format.html { redirect_to pool_path(@job_application_pool), notice: "Job application pool was successfully created." }
        format.json { render json: @job_application_pool, status: :created, location: @job_application_pool }
      rescue ActiveRecord::ActiveRecordError => error
        logger.error("Attempt to save new JobApplicationPool record failed -> (#{error})")
        flash[:error] = "Attempt to save new JobApplicationPool record failed"
        format.html { render action: "new" }
        format.json { render json: @job_application_pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /job_application_pools/:id(.:format)
  def update
    @job_application_pool = JobApplicationPool.find(params[:id])

    respond_to do |format|
      begin
        @job_application_pool.update_attributes(params[:job_application_pool])
        format.html { redirect_to pool_path(@job_application_pool), notice: "Job application pool was successfully updated." }
        format.json { head :no_content }
      rescue ActiveRecord::ActiveRecordError => error
        logger.error("Attempt to update JobApplicationPool record ID #{params[:id]} failed -> (#{error})")
        flash[:error] = "Attempt to update JobApplicationPool record ID #{params[:id]} failed"
        format.html { render action: "edit" }
        format.json { render json: @job_application_pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_application_pools/:id(.:format)
  def destroy
    @job_application_pool = JobApplicationPool.find(params[:id])
    @job_application_pool.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Job application pool #{params[:id]} was deleted." }
      format.json { head :no_content }
    end
  end
end

app/helpers/job_application_pools_helper.rb
module JobApplicationPoolsHelper
end

app/views/job_application_pools/_edit_form.html.haml
= form_for(@job_application_pool, :url => pool_path) do |f|
 %fieldset
  %legend Job Application Pool
  - if @job_application_pool.errors.any?
   %div#error_explanation
    %h2 #{pluralize(@job_application_pool.errors.count, "error")} prohibited this job application pool from being saved:
    %ul
     - @job_application_pool.errors.full_messages.each do |msg|
      %li #{msg}
  .field
   = f.label :user
   = f.text_field :user
  .field
   = f.label :description
   = f.text_area :description, :rows => 2
  .action
   = f.submit(value="Update")

app/views/job_application_pools/_form.html.haml
= form_for(@job_application_pool, :url => pools_path) do |f|
 %fieldset
  %legend New Job Application Pool
  - if @job_application_pool.errors.any?
   %div#error_explanation
    %h2 #{pluralize(@job_application_pool.errors.count, "error")} prohibited this job application pool from being saved:
    %ul
     - @job_application_pool.errors.full_messages.each do |msg|
      %li #{msg}
  .field
   = f.label "User:"
   = f.text_field :user
  .field
   = f.label "Pool Description:"
   = f.text_area :description, :rows => 2
  .action
   = f.submit(value="Create")

app/views/job_application_pools/_job_application_pool.html.haml
%tr.job-application-pool-entry{:id => ["JobApplicationPool", job_application_pool.id]}
 %td= job_application_pool.user
 %td(title="#{job_application_pool.job_applications.count} job application(s). Last updated #{job_application_pool.updated_at.strftime('%d/%m/%y %T')}")
  =job_application_pool.description
 = render :partial => "job_application_pool_links", :locals => { :job_application_pool => job_application_pool }

app/views/job_application_pools/_job_application_pool_links.html.haml
%td= link_to("", pool_applications_path(job_application_pool), class: "show-icon", title: "Show all job applications belonging to this pool")
%td= link_to("", edit_pool_path(job_application_pool), class: "edit-icon", title: "Edit this pool")
%td= link_to("", pool_path(job_application_pool), class: "delete-icon", title: "Delete this pool", method: :delete, data: { confirm: "Are you sure?" })

app/views/job_application_pools/edit.html.haml
%div.five.columns
 %span.link-back
  = link_to("Back", root_path)
%div.eleven.columns
 = render "edit_form"

app/views/job_application_pools/new.html.haml
%div.five.columns
 %span.link-back
  = link_to("Back", root_path)
%div.eleven.columns
 = render "form"

app/views/job_application_pools/new.js.erb
// -*- javascript -*-
$('div#forms').hide().after("<%= escape_javascript(render :partial => 'form') %>")
    .slideDown(2000, function() {
	console.log("Displaying form...");
    });

app/views/job_application_pools/show.html.haml
%div.five.columns
 %span.link-back
  = link_to("Back to Pool List", root_path)
%div.eleven.columns

app/views/job_application_pools/welcome.html.haml
%div.five.columns
 
 %h4 Job Application Pools
 Welcome! A job application pool is a collection of job applications, grouped for
 easy reference. 
 - if @job_application_pools.empty?
  Create a new pool using the form on the right.
 - else
  The current pools on this system are shown in the table on the
  right.
  %p
%div.eleven.columns
 - if @job_application_pools.empty?
  = render :partial => "job_application_pools/form"
 - else
  %div.job-application-pools
   %table
    %thead
     %tr
      %th User
      %th Description
      %th
      %th
      %th= link_to "", new_pool_path, remote: true, class: "add-icon", title: "Create a new job application pool", :disable_with => "Submitting.."
    %tbody
     = render :partial => @job_application_pools
  %div#forms
%br.clear