config/routes.rb
IJobDossier::Application.routes.draw do
  root :to => 'job_application_pools#welcome'

  resources :job_application_pools, :as => 'pools' do
    resources :job_applications, :as => "applications" do
      member do
        get :target
        get :dossier
      end
    end
  end

  resources :dossiers do
    resource :curriculum_vitae, :as => 'cv'
    resource :cover_letter, :as => 'cletter' do
      resources :cover_letter_parts, :as => 'part', :only => [ :show, :create, :update, :destroy ]
    end
    resources :references, :as => 'ref'
    resources :work_certificates, :as => 'wcert'
  end

end

app/models/job_application.rb
# == Schema Information
#
# Table name: job_applications
#
#  id                      :integer          not null, primary key
#  job_application_pool_id :integer
#  jobtitle                :string(255)
#  jobref                  :string(255)
#  deadline                :date
#  submission              :date
#  status                  :integer
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class JobApplication < ActiveRecord::Base
  attr_accessible :job_application_pool_id, :jobtitle, :jobref, :deadline, :submission, :status

  has_one :application_target
  has_one :dossier

  belongs_to :job_application_pool

  validates :jobtitle, presence: true
  validates :jobref,   presence: true
  validates :deadline, presence: true
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  layout "main"

  # GET /job_application_pools/:pool_id/job_applications/:id/target(.:format) target_pool_application
  def target
    @target = JobApplication.find(params[:id]).application_target

    respond_to do |format|
      format.json { render json: @target }
    end
  end

  # GET /job_application_pools/:pool_id/job_applications/:id/dossier(.:format) dossier_pool_application
  def dossier
    @dossier = JobApplication.find(params[:id]).dossier

    respond_to do |format|
      format.json { render json: @dossier }
    end
  end

  # GET /job_application_pools/:pool_id/job_applications(.:format) pool_applications
  def index
    @job_applications = JobApplicationPool.find(params[:pool_id]).job_applications.order('ID asc')
    if @job_applications.empty?
      @job_application = JobApplication.new
      @application_target = ApplicationTarget.new
      @dossier = Dossier.new
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @job_applications }
    end
  end

  # GET /job_application_pools/:pool_id/job_applications/:id(.:format) pool_application
  def show
    @job_application = JobApplication.find(params[:id])
    @application_target = @job_application.application_target
    @dossier = @job_application.dossier

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job_application }
    end
  end

  # GET /job_application_pools/:pool_id/job_applications/new(.:format) new_pool_application_path
  def new
    @job_application = JobApplication.new
    @application_target = ApplicationTarget.new
    @dossier = Dossier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job_application }
    end
  end

  # GET /job_application_pools/:pool_id/job_applications/:id/edit(.:format) edit_pool_application
  def edit
    @job_application = JobApplication.find(params[:id])
    @application_target = @job_application.application_target
    @dossier = @job_application.dossier
  end

  # POST job_application_pools/:pool_id/job_applications(.:format)
  def create
    respond_to do |format|
      begin
        @pool = JobApplicationPool.find(params[:pool_id])
        @job_application = JobApplication.new(params[:job_application])
        @application_target = ApplicationTarget.new(params[:application_target])
        @dossier = Dossier.new(params[:dossier])

        if @job_application.valid?
          if @application_target.valid?
            @job_application.save!
            @job_application.application_target=@application_target
            @job_application.dossier=@dossier
            @pool.job_applications << @job_application

            flash[:notice] = "Job application was successfully created."
            format.html { redirect_to :action => "show", :id => @job_application.id,
                                      :pool_id => @job_application.job_application_pool_id }
            format.json { render json: @job_application, status: :created, location: @job_application }
          else
            format.html { render action: "new" }
            format.json { render json: @application_target.errors, status: :unprocessable_entity }
          end
        else
          format.html { render action: "new" }
          format.json { render json: @job_application.errors, status: :unprocessable_entity }
        end
      rescue ActiveRecord::ActiveRecordError => error
        logger.error("Attempt to save new JobApplication record failed -> (#{e})")
        flash[:error] = "Attempt to save new JobApplication record failed"
        format.html { render action: "new" }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /job_application_pools/:pool_id/job_applications/:id(.:format)
  def update
    respond_to do |format|
      begin
        @job_application = JobApplication.find(params[:id])
        @application_target = @job_application.application_target
        @dossier = @job_application.dossier.update_attributes(params[:dossier])

        if @job_application.update_attributes(params[:job_application])
          if @application_target.update_attributes(params[:application_target])
            flash[:notice] = "Job application was successfully updated."
            format.html { redirect_to :action => "show", :id => @job_application.id, :pool_id => @job_application.job_application_pool_id }
            format.json { head :no_content }
          else
            format.html { render action: "edit" }
            format.json { render json: @application_target.errors, status: :unprocessable_entity }
          end
        else
          format.html { render action: "edit" }
          format.json { render json: @job_application.errors, status: :unprocessable_entity }
        end
      rescue ActiveRecord::RecordInvalid => error
        logger.error("Attempt to update JobApplication record #{params[:id]} failed -> (#{e})")
        flash[:error] = "Attempt to save new JobApplication record #{params[:id]} failed"
        format.html { render action: "new" }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_application_pools/:pool_id/job_applications/:id(.:format)
  def destroy
    @job_application = JobApplication.find(params[:id])
    @job_application.destroy

    respond_to do |format|
      format.html { redirect_to pool_applications_path, notice: "Job application #{params[:id]} was deleted." }
      format.json { head :no_content }
    end
  end
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/views/job_applications/_application_target.html.haml
- if @application_target.errors.any?
 %div#error_explanation
  %h2 #{pluralize(@application_target.errors.count, "error")} prohibited this application target from being saved:
  %ul
   - @application_target.errors.full_messages.each do |msg|
    %li #{msg}
= fields_for :application_target do |target|
 .field
  = target.label "Company:"
  = target.text_field :company
 .field
  = target.label "Contact:"
  = target.text_field :contact
 .field
  = target.label "Address:"
  = target.text_area :address, :rows => 3
 .field
  = target.label "Email:"
  = target.email_field :email
 .field
  = target.label "Notes:"
  = target.text_area :notes, :rows => 4

app/views/job_applications/_dossier.html.haml
= fields_for :dossier do |dossier|
 .field
  = dossier.label "Notes:"
  = dossier.text_area :notes, :rows => 4

app/views/job_applications/_full_edit_form.html.haml
= form_for(@job_application, :url => pool_application_path) do |f|
 %fieldset.job_application
  %legend Edit Job Application
  - if @job_application.errors.any?
   %div#error_explanation
    %h2 #{pluralize(@job_application.errors.count, "error")} prohibited this job application from being saved:
    %ul
     - @job_application.errors.full_messages.each do |msg|
      %li #{msg}
  .field
   = f.label "Title:"
   = f.text_field :jobtitle
  .field
   = f.label "Reference:"
   = f.text_field :jobref
  .field
   = f.label "Deadline:"
   = f.date_select :deadline, :order => [:day, :month, :year], :use_month_numbers => true
  .field
   = f.label "Submitted:"
   = f.date_select :submission, :order => [:day, :month, :year], :use_month_numbers => true, :include_blank => true
  .field
   = f.label "Status:"
   = f.select(:status, [ [ "dossier incomplete", 0], [ "dossier complete", 1 ] ], { :selected => 0 }, { :class => "incomplete" })

 %fieldset.application_target
  %legend Application Target
  = render "application_target"

 %fieldset.dossier
  %legend Dossier
  = render "dossier"

  .action
   = f.submit(value="Update")

app/views/job_applications/_full_form.html.haml
= form_for(@job_application, :url => pool_applications_path) do |f|
 %fieldset.job_application
  %legend New Job Application
  - if @job_application.errors.any?
   %div#error_explanation
    %h2 #{pluralize(@job_application.errors.count, "error")} prohibited this job application from being saved:
    %ul
     - @job_application.errors.full_messages.each do |msg|
      %li #{msg}
  .field
   = f.label "Title:"
   = f.text_field :jobtitle
  .field
   = f.label "Reference:"
   = f.text_field :jobref
  .field
   = f.label "Deadline:"
   = f.date_select :deadline, :order => [:day, :month, :year], :use_month_numbers => true
  .field
   = f.label "Submitted:"
   = f.date_select :submission, :order => [:day, :month, :year], :use_month_numbers => true, :include_blank => true
  .field
   = f.label "Status:"
   = f.select(:status, [ [ "dossier incomplete", 0], [ "dossier complete", 1 ] ], { :selected => 0 }, { :class => "incomplete" })

 %fieldset.application_target
  %legend Application Target
  = render "application_target"

 %fieldset.dossier
  %legend Dossier
  = render "dossier"

  .action
   = f.submit(value="Create")

app/views/job_applications/_job_application.html.haml
%tr.job-application-entry(title="This application is #{job_application.status == 0 ? 'incomplete' : 'complete'}"){:id => ["JobApplication", job_application.id]}
 %td= job_application.jobtitle
 %td= job_application.jobref
 %td= job_application.deadline.strftime("%d/%m/%y")
 %td= job_application.updated_at.strftime("%d/%m/%y %T")
 - if job_application.submission.nil?
  %td.submission{title: "Application not yet submitted so no date set"} -
 - else
  %td.submission-closed= job_application.submission.strftime("%d/%m/%y")
 = render :partial => "job_application_links", :locals => { :job_application => job_application }

app/views/job_applications/_job_application_links.html.haml
%td= link_to("", { :controller => "job_applications", :action => "show", :id => job_application, :pool_id => job_application.job_application_pool_id }, class: "show-icon", title: "Show this job application")
%td= link_to("", { :controller => "job_applications", :action => "edit", :id => job_application, :pool_id => job_application.job_application_pool_id }, class: "edit-icon", title: "Edit this job application")
%td= link_to("", { :controller => "job_applications", :action => "destroy", :id => job_application, :pool_id => job_application.job_application_pool_id }, 
                 { class: "delete-icon", title: "Delete this job application", method: :delete, data: { confirm: "Are you sure?" } })

app/views/job_applications/edit.html.haml
%div.five.columns
 %span.link-back
  = link_to("Show", pool_application_path)
  = link_to("Back", pool_applications_path)
%div.eleven.columns
 = render "full_edit_form"

app/views/job_applications/index.html.haml
%div.five.columns

 %h4 Job Applications
 - if @job_applications.empty?
  To add a new job application to the current pool, use the form on
  the right.

 - else
  The job applications belonging to the current pool are shown in the
  table on the right.
 %br
 %span.link-back
  = link_to("Back to Pool List", root_path, class: "home-icon")

%div.eleven.columns
 - if @job_applications.empty?
  = render :partial => "job_applications/full_form"
 - else
  %div.job-applications
   %table
    %thead
     %tr
      %th Job Title
      %th Ref
      %th Deadline
      %th Last Update
      %th Submitted
      %th
      %th
      %th= link_to "", new_pool_application_path, class: "add-icon", title: "Add a new job application to the current pool"
    %tbody
     = render :partial => @job_applications
%br.clear

app/views/job_applications/new.html.haml
%div.five.columns
 %span.link-back
  = link_to("Back", pool_applications_path)
%div.eleven.columns
 = render "full_form"

app/views/job_applications/show.html.haml
%div.five.columns
 %span.link-back
  = link_to("Edit", edit_pool_application_path)
  = link_to("Back", pool_applications_path)
 %p

%div.eleven.columns
 %p
 %table.job-application
  %tbody
   %tr
    %td.field-title Job Title:
    %td= @job_application.jobtitle
   %tr
    %td.field-title Reference:
    %td= @job_application.jobref
   %tr
    %td.field-title Deadline:
    %td= @job_application.deadline.strftime("%d/%m/%y")
   %tr
    %td.field-title Status:
    %td= @job_application.status

 %table.application-target
  %tbody
   %tr
    %td.field-title Company:
    %td= @job_application.application_target.company

 %table.dossier
  %tbody
   %tr
    %td.field-title Dossier notes:
    %td= @job_application.dossier.notes

 %div#accordion
  %h6 CV
  %div
   Show the CV here.
  %h6 References
  %div
   List the references here.
  %h6 Work Certificates
  %div
   List the work certificates here.

%br.clear